<?php

/**
 * @file
 * Contains multistep.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function multistep_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the multistep module.
    case 'help.page.multistep':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('formulaire multi step v2') . '</p>';
      return $output;

    default:
  }
}
